### ISSUE TITLE
Add Gz conversion step in juicebox_dump.py 

### ISSUE THREAD

**Issue by lmangnier** [broadinstitute/ABC-Enhancer-Gene-Prediction#13]
Hi, 

I launched your code on my own data (neurons) and It seems in the juicebox_dump.py step it misses a gz conversion for hic normalized files. Your python scripts for ABC score computation or powerlaw fitting wait a gz extension file and juicebox_dumb.py does not do it automatically. I did myself manually but you should probably add it in the code. 

Loïc.

**Comment by cmonger** [comment]
This (error due to no gz conversion step) also occurs when running juicer tools to download the example hic data if following the code provided on the readme:

#Download hic matrix file from juicebox
python src/juicebox_dump.py \
--hic_file https://hicfiles.s3.amazonaws.com/hiseq/k562/in-situ/combined_30.hic \
--juicebox "java -jar juicer_tools.jar" \
--outdir example_chr22/input_data/HiC/raw/ \
--chromosomes 22
#Fit HiC data to powerlaw model and extract parameters
python src/compute_powerlaw_fit_from_hic.py \
--hicDir example_chr22/input_data/HiC/raw/ \
--outDir example_chr22/input_data/HiC/raw/powerlaw/ \
--maxWindow 1000000 \
--minWindow 5000 \
--resolution 5000 \
--chr 'chr22'

**Comment by jnasser3** [comment]
Thank you both for reporting this. This is now the default behavior in v0.2.1
