### ISSUE TITLE
Hi-C data for mouse?

### ISSUE THREAD

**Issue by Amandez** [broadinstitute/ABC-Enhancer-Gene-Prediction#20]
Thank you for your tool.
I would like to use your tool with mouse  H3K27ac and ATAC-seq data (mm10); however it seems that your average Hi-C data is only for human. I've tried to run your tool without the Hi-C data, but it doesn't work. Is it possible to skip the Hi-C step, or do you have Hi-C data for mouse (mm10)?
Cheers

**Comment by jnasser3** [comment]
Hi, thanks for the interest.

We do not have average Hi-C data for mouse at the moment. 

It should be possible to run the model without Hi-C data, in this case the code will estimate the Contact component of the ABC score using the powerlaw relationship. In order to do this you must use the flag '--score_column powerlaw.Score' in the src/predict.py command.

If this does not work, then we could try to debug it.

**Comment by Amandez** [comment]
It works. Thank you
